"""Shared navel-gazing filter — single source of truth for what
counts as a consumerless artifact.

Originally lived inside ``tools/goals/dream_tool.py``; extracted to
its own module in ABE Phase 7 so the new ``company_set_product``
tool can apply the same filter to operator-or-agent-proposed
``what_we_sell`` text. The dream tool re-exports the names for
backwards compat.

The banlist came from real production output: the 2026-05-22/23
mind_actions log showed ~140 consumerless identity goals in 14h all
generated by the dream phase before this filter existed (Evidence
Garden, Self-Perception Diff Report, Two-Register Voice Atlas, …).
Every fragment in ``_BANNED_TITLE_FRAGMENTS`` was observed in that
production set.

See ``docs/76-ABE-FRAMEWORK.md`` §Phase 7 for the design contract.
"""

from __future__ import annotations

from typing import Any

# Banned fragments observed in real production navel-gazing output.
# Matched case-insensitively. Keep this list deterministic — the
# whole point is that the rejection is not LLM-discretion.
_BANNED_TITLE_FRAGMENTS: tuple[str, ...] = (
    "self-perception",
    "self perception",
    "self-image",
    "self image",
    "self-mythology",
    "identity audit",
    "identity ledger",
    "identity map",
    "identity trace",
    "identity memory",
    "identity debt",
    "identity claim",
    "evidence garden",
    "evidence-weighted",
    "evidence weighted",
    "acceptance handshake",
    "correction memory",
    "correction-to-identity",
    "completion contract",
    "receipt chain",
    "claim permission",
    "two-register voice",
    "role-boundary atlas",
    "first-person claim",
    "honesty mirror",
    "honesty drill",
)


# Words/phrases that signal an internal-only deliverable. Only
# triggers a rejection when the consumer is ALSO the agent itself —
# a "rubric" delivered to "the operator deciding X" is fine; a
# "rubric" with no clear external consumer is the failure mode.
_INTERNAL_ARTIFACT_HINTS: tuple[str, ...] = (
    "rubric",
    "atlas",
    "taxonomy",
    "ledger",
    "schema",
    "registry",
    "framework",
    "contact sheet",
    "internal note",
    "self-",
)


# Markers in a consumer string that name the agent itself rather
# than an outside party. "operator" / "user" override the check so
# "the agent operator deciding X" is valid.
_AGENT_SELF_MARKERS: tuple[str, ...] = (
    "the agent",
    "this agent",
    "myself",
    "the mind",
    "future cycle",
    "next cycle",
    "agent itself",
    "the system itself",
)


def is_consumerless(candidate: dict[str, Any]) -> tuple[bool, str]:
    """Detect candidates whose only beneficiary is the agent itself.

    Returns ``(is_consumerless, reason)``. Three signals, any of which
    rejects:
      1. Title matches a banned navel-gazing fragment.
      2. ``consumer`` field is missing, empty, or names the agent.
      3. ``consumer_artifact`` reads as an internal-only artifact AND
         the consumer string also references the agent itself.

    Rule 3 is deliberately conjunctive — a "rubric" delivered to "the
    operator deciding X" is fine; a "rubric" with no clear external
    consumer is the failure mode.
    """
    title = str(candidate.get("title", "")).lower()
    for frag in _BANNED_TITLE_FRAGMENTS:
        if frag in title:
            return True, f"title contains banned navel-gazing fragment: {frag!r}"

    consumer = str(candidate.get("consumer", "")).strip().lower()
    if not consumer:
        return True, "missing required 'consumer' field"

    consumer_is_self = any(m in consumer for m in _AGENT_SELF_MARKERS)
    if consumer_is_self and "operator" not in consumer and "user" not in consumer:
        return True, f"consumer is the agent itself: {consumer!r}"

    artifact = str(candidate.get("consumer_artifact", "")).strip().lower()
    if consumer_is_self and any(h in artifact for h in _INTERNAL_ARTIFACT_HINTS):
        return True, (
            f"artifact reads as internal-only ({artifact!r}) and consumer "
            f"is the agent itself"
        )

    return False, ""


def is_consumerless_text(
    text: str,
    *,
    label: str = "text",
) -> tuple[bool, str]:
    """Lighter-weight check for a free-text field (e.g.
    ``what_we_sell`` on a company.yaml). Only the title-fragment
    banlist applies — there's no separate consumer/artifact field
    to evaluate, so the conjunctive Rule 3 above doesn't fire.

    Returns ``(is_consumerless, reason)``. Used by
    ``company_set_product`` to reject agent-proposed product
    descriptions that drift back into the navel-gazing pattern.
    """
    if not text or not text.strip():
        return True, f"{label} is empty"

    lowered = text.lower()
    for frag in _BANNED_TITLE_FRAGMENTS:
        if frag in lowered:
            return True, (f"{label} contains banned navel-gazing fragment: {frag!r}")
    return False, ""
